@startuml

legend
event-source: next-u8
endlegend

[*] -> read_magic_number_1

read_magic_number_1: Read the first byte of a PBM image.  It is expecting
read_magic_number_1: to be a letter "P".
read_magic_number_1:
read_magic_number_1: entry-action: p4-init-result
read_magic_number_1 --> [*]: u8:eof-object? -> throw-unexpected-eof
read_magic_number_1 --> read_magic_number_2: u8:letter-P?
read_magic_number_1 --> [*]: guard:#t -> throw-magic-number-error

read_magic_number_2: Read the second byte of a PBM image.  It is expecting
read_magic_number_2: to be a single digit "1".
read_magic_number_2 --> [*]: u8:eof-object? -> throw-unexpected-eof
read_magic_number_2 --> lookup_width: u8:digit-four?
read_magic_number_2 --> [*]: guard:#t -> throw-magic-number-error

lookup_width: Lookup the image width value.
lookup_width --> [*]: u8:eof-object? -> throw-unexpected-eof
lookup_width -> read_width: u8:digit? -> push-event-to-buffer
lookup_width -> lookup_width: u8:newline?
lookup_width --> read_comment: u8:number-sign?
lookup_width -> lookup_width: u8:space?
lookup_width --> [*]: guard:#t -> throw-format-error

read_width: Read the image width value.
read_width --> [*]: u8:eof-object? -> throw-unexpected-eof
read_width --> lookup_height: u8:space? -> set-width/binary
read_width -> read_width: u8:digit? -> push-event-to-buffer
read_width --> [*]: guard:#t -> throw-format-error

lookup_height: Lookup the image height value.
lookup_height -> lookup_height: u8:space?
lookup_height -> read_height: u8:digit? -> push-event-to-buffer
lookup_height --> [*]: guard:#t -> throw-format-error

read_height: Read the image height value.
read_height -> read_data: u8:newline? -> set-height/binary
read_height -> read_height: u8:digit? -> push-event-to-buffer
read_height --> [*]: guard:#t -> throw-format-error

read_data: Read the image data.
read_data --> validate_image: u8:eof-object? -> p4-set-data
read_data -> read_data: guard:#t -> push-event-to-buffer

read_comment --> [*]: u8:eof-object? -> throw-unexpected-eof
read_comment --> lookup_width: u8:newline? -> append-comment/binary
read_comment -> read_comment: guard:#t -> push-event-to-buffer

validate_image: event-source: none
validate_image: entry-action: p4-validate-image
validate_image --> [*]

@enduml

